"""Shared helpers and constants for the mock data package."""

from __future__ import annotations

import random
from typing import Any

MOCK_NOTE = (
    "Placeholder data generated by the Q-Compass prototype. No classical ML "
    "model, quantum circuit or recommendation engine has been executed yet."
)

TASK_TYPE_OPTIONS = [
    ("Binary Classification", 0.88, ["classify", "predict", "churn", "fraud", "detect", "label"]),
    ("Multi-class Classification", 0.79, ["classify", "category", "segment", "image", "multi"]),
    ("Regression", 0.82, ["regress", "estimate", "price", "forecast", "revenue"]),
    ("Clustering", 0.74, ["cluster", "segment", "group", "anomaly"]),
    ("Time Series Forecasting", 0.77, ["forecast", "time", "trend", "demand", "sequence"]),
]

PROBLEM_KEYWORDS = [
    "customer", "churn", "retention", "classification", "tabular", "historical",
    "behaviour", "risk", "revenue", "operations", "features", "prediction",
]

APPROACH_LABELS = {"classical": "Classical AI", "quantum": "Quantum AI", "hybrid": "Hybrid AI"}


def rng_for(seed: str) -> random.Random:
    """Return a deterministic RNG seeded from ``seed``.

    Determinism matters for demos: the same upload always yields the same
    report, so screenshots and walkthroughs are reproducible.
    """
    return random.Random(f"q-compass::{seed}")


def rnd(value: float, digits: int = 2) -> float:
    return round(float(value), digits)


def pick_task_type(description: str) -> tuple[str, float]:
    """Infer a task type from the problem description (mock keyword matching)."""
    text = (description or "").lower()
    if not text.strip():
        return "Binary Classification", 0.62
    for name, base_confidence, hints in TASK_TYPE_OPTIONS:
        hits = sum(1 for hint in hints if hint in text)
        if hits:
            return name, rnd(min(0.97, base_confidence + 0.04 * (hits - 1)), 2)
    return "Binary Classification", 0.55
